import { ArrowLeft, Brain, TrendingUp, AlertTriangle, CheckCircle } from 'lucide-react';
import { useNavigate } from 'react-router';

export function HealthSummary() {
  const navigate = useNavigate();

  return (
    <div className="size-full bg-background overflow-auto">
      <div className="px-6 py-6 pb-24">
        <div className="flex items-center gap-3 mb-6">
          <button onClick={() => navigate(-1)} className="p-2 rounded-xl hover:bg-muted transition-colors">
            <ArrowLeft className="w-6 h-6 text-foreground" />
          </button>
          <div>
            <h1 className="text-xl text-foreground">
              AI Health Summary
            </h1>
            <p className="text-sm text-muted-foreground">Generated insights</p>
          </div>
        </div>

        <div className="bg-gradient-to-br from-primary to-secondary rounded-3xl p-6 mb-6 text-white shadow-xl">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-12 h-12 rounded-2xl bg-white/20 backdrop-blur flex items-center justify-center">
              <Brain className="w-6 h-6 text-white" />
            </div>
            <div>
              <p className="text-white/80 text-sm">Overall Health Status</p>
              <h2 className="text-xl">Good Condition</h2>
            </div>
          </div>
          <p className="text-white/90 text-sm leading-relaxed">
            Based on your health profile and lifestyle data, your overall health is in good condition with some areas for improvement.
          </p>
        </div>

        <div className="space-y-4">
          <div className="bg-white rounded-2xl p-5 border border-border">
            <div className="flex items-start gap-3 mb-3">
              <div className="w-10 h-10 rounded-xl bg-green-500/10 flex items-center justify-center flex-shrink-0">
                <CheckCircle className="w-5 h-5 text-green-600" />
              </div>
              <div className="flex-1">
                <h3 className="text-sm text-foreground mb-1">Strengths</h3>
                <ul className="space-y-1">
                  <li className="text-sm text-muted-foreground">• Healthy BMI within normal range</li>
                  <li className="text-sm text-muted-foreground">• Good water intake habits</li>
                  <li className="text-sm text-muted-foreground">• Regular exercise routine</li>
                  <li className="text-sm text-muted-foreground">• Normal blood pressure levels</li>
                </ul>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-2xl p-5 border border-border">
            <div className="flex items-start gap-3 mb-3">
              <div className="w-10 h-10 rounded-xl bg-orange-500/10 flex items-center justify-center flex-shrink-0">
                <AlertTriangle className="w-5 h-5 text-orange-600" />
              </div>
              <div className="flex-1">
                <h3 className="text-sm text-foreground mb-1">Areas for Improvement</h3>
                <ul className="space-y-1">
                  <li className="text-sm text-muted-foreground">• Sleep duration below recommended 8 hours</li>
                  <li className="text-sm text-muted-foreground">• Consider reducing alcohol intake</li>
                  <li className="text-sm text-muted-foreground">• Monitor asthma symptoms regularly</li>
                </ul>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-2xl p-5 border border-border">
            <div className="flex items-start gap-3 mb-3">
              <div className="w-10 h-10 rounded-xl bg-secondary/10 flex items-center justify-center flex-shrink-0">
                <TrendingUp className="w-5 h-5 text-secondary" />
              </div>
              <div className="flex-1">
                <h3 className="text-sm text-foreground mb-1">Recommendations</h3>
                <ul className="space-y-1">
                  <li className="text-sm text-muted-foreground">• Aim for 7-8 hours of sleep per night</li>
                  <li className="text-sm text-muted-foreground">• Continue regular exercise routine</li>
                  <li className="text-sm text-muted-foreground">• Schedule annual health checkup</li>
                  <li className="text-sm text-muted-foreground">• Keep asthma medication readily available</li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <div className="mt-6 bg-purple-50 border border-purple-200 rounded-2xl p-4">
          <p className="text-sm text-purple-900 mb-2">
            This summary is generated by AI based on your health data and should not replace professional medical advice.
          </p>
          <p className="text-xs text-purple-700">
            Last updated: May 3, 2026
          </p>
        </div>
      </div>
    </div>
  );
}
